server:
  port: 8089
spring:
  application:
    name: awei-gateway
  profiles:
    active: local
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:8718
        #这里的配置时sentinel整合网关的时候用到的配置，暂时不用看
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel-poem-gateway
            group: DEFAULT_GROUP
            data-type: json
            rule-type: flow
