# application.yml
server:
  port: 8081
spring:
  application:
    name: auth
  profiles:
    active: local
  cloud:
    nacos:
      config:
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
        namespace: 292fb7b3-e28a-4e3e-981c-8ff4697da627
        server-addr: 163.172.222.78:8848
  config:
    import:
#      - optional:nacos:test.yml  # 监听 DEFAULT_GROUP:test.yml
#      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml # 覆盖默认 group，监听 group_01:test01.yml
      - nacos:${spring.application.name}-${spring.profiles.active}.yaml # 在拉取nacos配置异常时会快速失败，会导致 spring 容器启动失败
